id: ACA7AB545
title: Consecrating the Vase for the Practice of the Great Compassionate One, Natural
  Liberation of Suffering (Dukngal Rangdrol)
type: translation
pechas:
- I0D788192
- I690CBCBF
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:55:01.139114
  last_modified_at: 2023-01-04 11:55:01.139125
  collections:
  - Fourth Dodrupchen Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I0D788192/6A53: 4D8F
  I690CBCBF/2793: 4D8F
